[package]
name = "email_newsletter"
version = "0.1.0"
authors = ["Vitor Aquino"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "email_newsletter"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.0"
reqwest = "0.11.14"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
